export interface Season {
    id?: number,
    number: number,
    title_japanese: string,
    title_english: string,
    synopsis: string,
    year: number,
    season_year: string,
    type: string,
    studio: string,
    image: string,
    cover_image: string,
    cover_image_secondary: string,
    url_trailer: string,
    status: boolean,
    animeId: number,
}